services:
  growthbook:
    image: "growthbook/growthbook:latest"
    ports:
      - "3000:3000"
      - "3100:3100"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - APP_ORIGIN=https://growthbook.dev.pelago.co
      - API_HOST=https://growthbook.dev.pelago.co
      - JWT_SECRET=${JWT_SECRET}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - NODE_ENV=production
      - COOKIE_SECURE=true
      - COOKIE_SAME_SITE=none
      - TRUSTED_PROXIES=172.0.0.0/8,127.0.0.1,::1
      - CORS_ORIGIN=https://growthbook.dev.pelago.co
      - DISABLE_CACHE=true
      - CACHE_CONTROL=no-cache, no-store, must-revalidate
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_PORT=587
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
    networks:
      - growthbook_network

  exposure-api:
    build:
      context: ./exposure-api
      dockerfile: Dockerfile.exposure
    ports:
      - "8000:8000"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
      - KAFKA_EXPOSURE_TOPIC=exposures
      - DB_HOST=${DB_HOST}
      - DB_PORT=5439
      - DB_NAME=events
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - growthbook_network

  growthbook-consumer:
    build:
      context: ./growthbook-consumer
      dockerfile: Dockerfile.consumer
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
      - KAFKA_CONSUMER_GROUP=growthbook-consumer
      - KAFKA_EXPOSURE_TOPIC=exposures
      - DB_HOST=${DB_HOST}
      - DB_PORT=5439
      - DB_NAME=events
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - BATCH_SIZE=100
      - BATCH_TIMEOUT_SECONDS=30
      - MAX_RETRIES=3
      - AWS_DEFAULT_REGION=ap-southeast-1
    restart: unless-stopped
    networks:
      - growthbook_network

  nginx:
    image: "nginx:latest"
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - growthbook
      - exposure-api
    networks:
      - growthbook_network

networks:
  growthbook_network:
    driver: bridge