services:
  growthbook:
    image: "growthbook/growthbook:latest"
    environment:
      # DocumentDB connection string with SSL
      - MONGODB_URI=mongodb://pelago:i8jxrnMV6BJSLAkxopCCsXUdXygj8wYQ@growthbook-cluster-752221338939.ap-southeast-1.docdb-elastic.amazonaws.com:27017/growthbook?ssl=true&retryWrites=false&authSource=admin
      - APP_ORIGIN=https://growthbook.dev.pelago.co
      - API_HOST=https://growthbook.dev.pelago.co
      - JWT_SECRET=your-super-secure-jwt-secret-key-that-should-be-at-least-32-characters-long-for-security
      - ENCRYPTION_KEY=your-super-secure-encryption-key-that-should-be-at-least-32-characters-long-for-security
      - NODE_ENV=production
      - COOKIE_SECURE=true
      - COOKIE_SAME_SITE=none
      - TRUSTED_PROXIES=172.0.0.0/8,127.0.0.1,::1
      - CORS_ORIGIN=https://growthbook.dev.pelago.co
      - DISABLE_CACHE=true
      - CACHE_CONTROL=no-cache, no-store, must-revalidate
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_PORT=587
      - EMAIL_HOST_USER=your-email@gmail.com
      - EMAIL_HOST_PASSWORD=xxxxx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - growthbook_network

  exposure-api:
    build:
      context: ./exposure-api
      dockerfile: Dockerfile.exposure
    environment:
      - DB_HOST=event-warehouse.c42h0lx7fues.ap-southeast-1.redshift.amazonaws.com
      - DB_PORT=5439
      - DB_NAME=events
      - DB_USER=datascience
      - DB_PASSWORD=eyEnaG26eoTQahEsj6d66KafkDxs4TRv
    networks:
      - growthbook_network

  nginx:
    image: "nginx:latest"
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - growthbook
      - exposure-api
    networks:
      - growthbook_network

networks:
  growthbook_network:
    driver: bridge
