services:
  mongo:
    image: "mongo:latest"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodata:/data/db
  
  growthbook:
    image: "growthbook/growthbook:latest"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://root:password@mongo:27017/growthbook?authSource=admin
      - APP_ORIGIN=https://7770a5dbf3dd.ngrok-free.app
      - API_HOST=https://7770a5dbf3dd.ngrok-free.app
      - JWT_SECRET=your-super-secure-jwt-secret-key-that-should-be-at-least-32-characters-long-for-security
      - NODE_ENV=development
      - COOKIE_SECURE=true
      - COOKIE_SAME_SITE=none
      - TRUSTED_PROXIES=172.0.0.0/8,127.0.0.1,::1
      - CORS_ORIGIN=https://7770a5dbf3dd.ngrok-free.app
      - DISABLE_CACHE=true
      - CACHE_CONTROL=no-cache, no-store, must-revalidate
    volumes:
      - uploads:/usr/local/src/app/packages/back-end/uploads
  
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - growthbook
volumes:
  uploads:
  mongodata:
