services:
  mongo:
    image: "mongo:latest"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodata:/data/db
  
  growthbook:
    image: "growthbook/growthbook:latest"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://root:password@mongo:27017/growthbook?authSource=admin
      - APP_ORIGIN=http://13.251.13.232
      - API_HOST=http://13.251.13.232
      - JWT_SECRET=your-super-secure-jwt-secret-key-that-should-be-at-least-32-characters-long-for-security
      - NODE_ENV=production
      - COOKIE_SECURE=false
      - COOKIE_SAME_SITE=lax
      - TRUSTED_PROXIES=172.0.0.0/8,127.0.0.1,::1
      - CORS_ORIGIN=http://13.251.13.232
      - DISABLE_CACHE=true
      - CACHE_CONTROL=no-cache, no-store, must-revalidate
      - EMAIL_ENABLED=true
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_PORT=587
      - EMAIL_HOST_USER=aman@pelago.co
      - EMAIL_HOST_PASSWORD=xxxxx
      - EMAIL_FROM=GrowthBook <no-reply@pelago.co>
    volumes:
      - uploads:/usr/local/src/app/packages/back-end/uploads
  
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - growthbook
volumes:
  uploads:
  mongodata:
